# Dotfile specific
dotfiles_home: "{{ home }}/.dotfiles"
home: "{{ ansible_user_dir | expanduser }}"

# Git
git:
  user: lecoqjacob
  name: Jacob LeCoq
  email: lecoqjacob@gmail.com

# System
os: "{{ ansible_os_family }}"
sudo_use_password: true
username: "{{ ansible_user_id }}"
hostname: "{{ ansible_hostname }}"
shell: "{{ ansible_user_shell | default('/bin/zsh') }}"