---
roles:
  - name: gantsign.golang

collections:
  - name: kewlfft.aur # AUR packages

  - name: community.general
    source: https://galaxy.ansible.com

  - name: n16hth4wkk.workstation
    source: ./galaxy/n16hth4wkk/workstation
    type: dir