---
- name: Test the Hello World filter plugin
  ansible.builtin.set_fact:
    msg: "{{ 'ansible-creator' | n16hth4wkk.workstation.hello_world }}"

- name: Assert that the filter worked
  ansible.builtin.assert:
    that:
      - msg == 'Hello, ansible-creator'
