---
- name: Allow sudo without password
  become: true
  when: (not skip_setup) and (not SUDO_USE_PASSWORD)
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    validate: visudo -cf %s
    line: "{{ USERNAME }}\tALL=NOPASSWD: ALL"
    insertafter: ^%admin\tALL=\(ALL\) ALL

- name: Create directory ~/.local/bin/
  when: not skip_setup
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "755"

- name: Gather the package facts
  no_log: true
  ansible.builtin.package_facts:
    manager: auto

- name: Install generic packages
  # become: true
  ansible.builtin.package:
    state: latest
    name: "{{ system_packages.generic }}"

- name: Upgrade OS packages
  ansible.builtin.include_tasks: "{{ SYSTEM_ROLE_DIR }}/tasks/{{ ansible_os_family }}.yml"

- name: Run stow for /etc
  # become: true
  n16hth4wkk.general.stow:
    state: supress
    package: etc
    target: /etc
    dir: roles/system/files