---
- name: Base | Prompt SSH password if necessary
  when: (ansible_become_password | length <= 0) or (ansible_password | length <= 0)
  block:
    - name: Base | Conditionally prompt for ssh/sudo password
      no_log: true
      register: password_prompt
      ansible.builtin.pause:
        echo: false
        prompt: Password for {{ ansible_user_id }}@{{ ansible_host }}

    - name: Base | Set ansible_become_password
      no_log: true
      ansible.builtin.set_fact:
        ansible_password: "{{ password_prompt.user_input }}"
        ansible_become_password: "{{ password_prompt.user_input }}"

#####################
# Base | Bootstrap  #
#####################
- name: Base | Check if initial install
  no_log: true
  register: init_run
  when: not skip_setup
  ansible.builtin.stat:
    path: "{{ init_run_path }}"

- name: Base | Set skip_setup to true if initial run
  no_log: true
  when: not skip_setup
  ansible.builtin.set_fact:
    skip_setup: "{{ init_run.stat.exists }}"

- name: Base | Install collections and roles together
  when: not skip_setup
  community.general.ansible_galaxy_install:
    type: both
    requirements_file: requirements.yml

- name: Base | Install core packages
  when: not skip_setup
  ansible.builtin.package:
    state: latest
    name:
      - git
      - stow

- name: Base | Ensure dotfiles are present
  when: not skip_setup
  register: dotfiles_home
  ansible.builtin.stat:
    path: "{{ dotfiles_home }}"

- name: Base | Make sure dotfiles are present
  when: (not skip_setup) and (not dotfiles_home.stat.exists)
  ansible.builtin.git:
    repo: https://github.com/{{ git.user }}/dotfiles.git
    dest: ~/.dotfiles
    version: HEAD

#####################
# Base | ENV        #
#####################

- name: Base | Allow sudo without password
  become: true
  when: (not skip_setup) and (sudo_use_password)
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    validate: visudo -cf %s
    line: "{{ username }}\tALL=NOPASSWD: ALL"
    insertafter: ^%admin\tALL=\(ALL\) ALL

#####################
# Base | System     #
#####################

- name: Base | Create directory ~/.local/bin/
  when: not skip_setup
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: "755"

- name: Base | Install generic packages
  become: true
  ansible.builtin.package:
    state: latest
    name: "{{ base_packages.generic | union(base_additional_packages) | list | unique }}"

- name: Base | Upgrade OS packages
  ansible.builtin.include_tasks: "roles/base/tasks/{{ ansible_os_family }}.yml"

- name: Base | Update fonts # noqa no-changed-when
  when: not skip_setup
  ansible.builtin.shell:
    cmd: |-
      cp -vr $HOME/.fonts/* /usr/share/fonts/truetype/
      dpkg-reconfigure fontconfig
      fc-cache -fv